// This file is automatically generated, DO NOT EDIT!
// ==================================================

if (is_CSRRC)
	`OP <= OP_CSRRC;
else if (is_CSRRS)
	`OP <= OP_CSRRS;
else if (is_CSRRW)
	`OP <= OP_CSRRW;
else if (is_DIV)
	`OP <= OP_DIV;
else if (is_DIVU)
	`OP <= OP_DIVU;
else if (is_MUL)
	`OP <= OP_MUL;
else if (is_MULH)
	`OP <= OP_MULH;
else if (is_MULHU)
	`OP <= OP_MULHU;
else if (is_MRET)
	`OP <= OP_MRET;
else if (is_REM)
	`OP <= OP_REM;
else if (is_REMU)
	`OP <= OP_REMU;
