// This file is automatically generated, DO NOT EDIT!
// ==================================================

wire memory_read = 
	is_LB   |
	is_LBU  |
	is_LH   |
	is_LHU  |
	is_LW   |
	0;

wire memory_write = 
	is_SB   |
	is_SH   |
	is_SW   |
	0;

wire [2:0] memory_width = 
	is_LB   ? 3'd1 :
	is_LBU  ? 3'd1 :
	is_LH   ? 3'd2 :
	is_LHU  ? 3'd2 :
	is_LW   ? 3'd4 :
	is_SB   ? 3'd1 :
	is_SH   ? 3'd2 :
	is_SW   ? 3'd4 :
	0;

wire memory_signed = 
	is_LB   |
	is_LH   |
	0;

