// This file is automatically generated, DO NOT EDIT!
// ==================================================

localparam OP_CSRRC  = 4'd1;
localparam OP_CSRRS  = 4'd2;
localparam OP_CSRRW  = 4'd3;
localparam OP_DIV    = 4'd4;
localparam OP_DIVU   = 4'd5;
localparam OP_FENCE  = 4'd6;
localparam OP_MUL    = 4'd7;
localparam OP_MULH   = 4'd8;
localparam OP_MULHU  = 4'd9;
localparam OP_MRET   = 4'd10;
localparam OP_REM    = 4'd11;
localparam OP_REMU   = 4'd12;
