// This file is automatically generated, DO NOT EDIT!
// ==================================================

localparam OP_DIV    = 5'd1;
localparam OP_DIVU   = 5'd2;
localparam OP_EBREAK = 5'd3;
localparam OP_ECALL  = 5'd4;
localparam OP_JAL    = 5'd5;
localparam OP_JALR   = 5'd6;
localparam OP_LB     = 5'd7;
localparam OP_LBU    = 5'd8;
localparam OP_LH     = 5'd9;
localparam OP_LHU    = 5'd10;
localparam OP_LW     = 5'd11;
localparam OP_LWU    = 5'd12;
localparam OP_MUL    = 5'd13;
localparam OP_MULH   = 5'd14;
localparam OP_MULHU  = 5'd15;
localparam OP_REM    = 5'd16;
localparam OP_REMU   = 5'd17;
localparam OP_SB     = 5'd18;
localparam OP_SH     = 5'd19;
localparam OP_SW     = 5'd20;
