// This file is automatically generated, DO NOT EDIT!
// ==================================================

// CSRRC
if (`EXECUTE_OP == OP_CSRRC) begin
	`RD <= csr_rd;
	csr_wr <= csr_rd & !`RS1;
	csr_wr_en <= 1;
	`EXECUTE_DONE;
end

// CSRRS
else if (`EXECUTE_OP == OP_CSRRS) begin
	`RD <= csr_rd;
	csr_wr <= csr_rd | `RS1;
	csr_wr_en <= 1;
	`EXECUTE_DONE;
end

// CSRRW
else if (`EXECUTE_OP == OP_CSRRW) begin
	`RD <= csr_rd;
	csr_wr <= `RS1;
	csr_wr_en <= 1;
	`EXECUTE_DONE;
end

// DIV
else if (`EXECUTE_OP == OP_DIV) begin
	if (`CYCLE == `DIV_CYCLE_LATENCY) begin
		`RD <= div_result[31:0];
		`EXECUTE_DONE;
	end
end

// DIVU
else if (`EXECUTE_OP == OP_DIVU) begin
	if (`CYCLE == `DIV_CYCLE_LATENCY) begin
		`RD <= div_result[31:0];
		`EXECUTE_DONE;
	end
end

// FENCE
else if (`EXECUTE_OP == OP_FENCE) begin
	o_mem_flush <= 1;
	`EXECUTE_DONE;
end

// MUL
else if (`EXECUTE_OP == OP_MUL) begin
	if (`CYCLE == `MUL_CYCLE_LATENCY) begin
		`RD <= mul_result[31:0];
		`EXECUTE_DONE;
	end
end

// MULH
else if (`EXECUTE_OP == OP_MULH) begin
	if (`CYCLE == `MUL_CYCLE_LATENCY) begin
		`RD <= mul_result[63:32];
		`EXECUTE_DONE;
	end
end

// MULHU
else if (`EXECUTE_OP == OP_MULHU) begin
	if (`CYCLE == `MUL_CYCLE_LATENCY) begin
		`RD <= mul_result[63:32];
		`EXECUTE_DONE;
	end
end

// MRET
else if (`EXECUTE_OP == OP_MRET) begin
	`GOTO(`MEPC);
	`EXECUTE_DONE;
end

// REM
else if (`EXECUTE_OP == OP_REM) begin
	if (`CYCLE == `DIV_CYCLE_LATENCY) begin
		`RD <= div_remainder[31:0];
		`EXECUTE_DONE;
	end
end

// REMU
else if (`EXECUTE_OP == OP_REMU) begin
	if (`CYCLE == `DIV_CYCLE_LATENCY) begin
		`RD <= div_remainder[31:0];
		`EXECUTE_DONE;
	end
end
