// This file is automatically generated, DO NOT EDIT!
// ==================================================

if (is_DIV)
	`OP <= OP_DIV;
else if (is_DIVU)
	`OP <= OP_DIVU;
else if (is_EBREAK)
	`OP <= OP_EBREAK;
else if (is_ECALL)
	`OP <= OP_ECALL;
else if (is_JAL)
	`OP <= OP_JAL;
else if (is_JALR)
	`OP <= OP_JALR;
else if (is_LB)
	`OP <= OP_LB;
else if (is_LBU)
	`OP <= OP_LBU;
else if (is_LH)
	`OP <= OP_LH;
else if (is_LHU)
	`OP <= OP_LHU;
else if (is_LW)
	`OP <= OP_LW;
else if (is_LWU)
	`OP <= OP_LWU;
else if (is_MUL)
	`OP <= OP_MUL;
else if (is_MULH)
	`OP <= OP_MULH;
else if (is_MULHU)
	`OP <= OP_MULHU;
else if (is_REM)
	`OP <= OP_REM;
else if (is_REMU)
	`OP <= OP_REMU;
else if (is_SB)
	`OP <= OP_SB;
else if (is_SH)
	`OP <= OP_SH;
else if (is_SW)
	`OP <= OP_SW;
