// This file is automatically generated, DO NOT EDIT!
// ==================================================

wire [3:0] alu_operation = 
	is_ADD ? `OP_SIGNED_ADD :
	is_ADDI ? `OP_SIGNED_ADD :
	is_ADDIW ? `OP_SIGNED_ADD :
	is_ADDW ? `OP_UNSIGNED_ADD :
	is_AND ? `OP_AND :
	is_ANDI ? `OP_AND :
	is_OR ? `OP_OR :
	is_ORI ? `OP_OR :
	0;

wire [31:0] alu_operand1 = 
	is_ADD ? i_rs1 :
	is_ADDI ? i_rs1 :
	is_ADDIW ? i_rs1 :
	is_ADDW ? i_rs1 :
	is_AND ? i_rs1 :
	is_ANDI ? i_rs1 :
	is_OR ? i_rs1 :
	is_ORI ? i_rs1 :
	0;

wire [31:0] alu_operand2 = 
	is_ADD ? i_rs2 :
	is_ADDI ? i_rs2 :
	is_ADDIW ? i_imm :
	is_ADDW ? i_rs2 :
	is_AND ? i_rs2 :
	is_ANDI ? i_imm :
	is_OR ? i_rs2 :
	is_ORI ? i_imm :
	0;

