// This file is automatically generated, DO NOT EDIT!
// ==================================================

wire [4:0] fpu_operation = 
	is_FADD    ? `FPU_OP_ADD :
	is_FCVT_W  ? `FPU_OP_INT :
	is_FDIV    ? `FPU_OP_DIV :
	is_FEQ     ? `FPU_OP_CMP_EQUAL :
	is_FLE     ? `FPU_OP_CMP_LEQUAL :
	is_FLT     ? `FPU_OP_CMP_LESS :
	is_FMADD   ? `FPU_OP_MADD :
	is_FMSUB   ? `FPU_OP_MSUB :
	is_FNMADD  ? `FPU_OP_NMADD :
	is_FNMSUB  ? `FPU_OP_NMSUB :
	is_FMUL    ? `FPU_OP_MUL :
	is_FMV_X_W ? `FPU_OP_MOV :
	is_FMV_W_X ? `FPU_OP_MOV :
	is_FSGNJ   ? `FPU_OP_SGNJ :
	is_FSGNJN  ? `FPU_OP_SGNJN :
	is_FSGNJX  ? `FPU_OP_SGNJX :
	is_FSUB    ? `FPU_OP_SUB :
	5'd0;

