// This file is automatically generated, DO NOT EDIT!
// ==================================================

if (is_DIV)
	`OP <= OP_DIV;
else if (is_DIVU)
	`OP <= OP_DIVU;
else if (is_MUL)
	`OP <= OP_MUL;
else if (is_MULH)
	`OP <= OP_MULH;
else if (is_MULHU)
	`OP <= OP_MULHU;
else if (is_REM)
	`OP <= OP_REM;
else if (is_REMU)
	`OP <= OP_REMU;
