// This file is automatically generated, DO NOT EDIT!
// ==================================================

localparam OP_DIV    = 3'd1;
localparam OP_DIVU   = 3'd2;
localparam OP_MUL    = 3'd3;
localparam OP_MULH   = 3'd4;
localparam OP_MULHU  = 3'd5;
localparam OP_REM    = 3'd6;
localparam OP_REMU   = 3'd7;
