// This file is automatically generated, DO NOT EDIT!
// ==================================================

// CSRRC
if (`EXECUTE_OP == OP_CSRRC) begin
	`RD <= csr_rd;
	csr_wr <= csr_rd & !`RS1;
	csr_wr_en <= 1;
	`EXECUTE_DONE;
end

// CSRRS
else if (`EXECUTE_OP == OP_CSRRS) begin
	`RD <= csr_rd;
	csr_wr <= csr_rd | `RS1;
	csr_wr_en <= 1;
	`EXECUTE_DONE;
end

// CSRRW
else if (`EXECUTE_OP == OP_CSRRW) begin
	`RD <= csr_rd;
	csr_wr <= `RS1;
	csr_wr_en <= 1;
	`EXECUTE_DONE;
end

// MRET
else if (`EXECUTE_OP == OP_MRET) begin
	`GOTO(`MEPC);
	`EXECUTE_DONE;
end
